name: TimeScheduler

services:
  mysql-primary:
    image: mysql:latest
    container_name: db-primary
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: timescheduler_master
    ports: 
      - "3306:3306"
    volumes:
      - master_data:/var/lib/mysql
    networks:
      - db_network

  mysql-replica:
    image: mysql:latest
    container_name: db-replica
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: timescheduler_slave
      MYSQL_TCP_PORT: 3307
    ports: 
      - "3307:3307"
    volumes:
      - slave_data:/var/lib/mysql
    networks:
      - db_network

volumes:
  master_data:
  slave_data:

networks:
  db_network: