name: TimeScheduler

services:
  mysql-primary:
    image: mysql:latest
    container_name: mysql-primary
    command: --server-id=1 --log-bin=mysql-bin --binlog-format=row
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: timescheduler
      MYSQL_TCP_PORT: 50400
    ports: 
      - "50400:50400"
    volumes:
      - master_data:/var/lib/mysql
    networks:
      - db_network

  mysql-replica:
    image: mysql:latest
    container_name: mysql-replica
    depends_on:
      - mysql-primary
    command: --server-id=2 --log-bin=mysql-bin --binlog-format=row
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: timescheduler
      MYSQL_TCP_PORT: 50401
    ports: 
      - "50401:50401"
    volumes:
      - slave_data:/var/lib/mysql
    networks:
      - db_network

volumes:
  master_data:
  slave_data:

networks:
  db_network: